### ISSUE TITLE
Do not prompt when installing plugins with Composer 2.2.x

### ISSUE THREAD

**Issue by anavarre** [acquia/drupal-minimal-project#19]
See https://github.com/acquia/drupal-recommended-project/issues/65

**Comment by mglaman** [comment]
This causes CI to break when tty

**Comment by anavarre** [comment]
@danepowell @grasmash looks like [we fixed this](https://github.com/acquia/drupal-recommended-project/commit/769b1a62b1bf5b829142a122a361e0e28598e108) for the recommended project only?
